### ISSUE TITLE
New namespace is not creating new secrets

### ISSUE THREAD

**Issue by jhonis** [ChistaDATA/cluster-secret-operator#7]
## Detailed Description
After creating a new namespace we couldn't find the secret which should be created by cluster-secret-operator on it.

## Context (Environment)
We have a ClusterSecret resource with the following namespace filtering:
```yaml
includeNamespaces:
  - '*'
excludeNamespaces:
  - '*system'
  - kube*
```

## Expected Behavior
When new namespace is created and its name matches the filter, a secret should be created there.

## Current Behavior
No secret is being created.

## Steps to Reproduce
1. Create a ClusterSecret with the above filter
2. Create a new namespace (e.g. `test`)
3. The secret can't be found
